import type { NextPage } from 'next';
import Head from 'next/head';
import Router from 'next/router';
import LoadingScreen from '../../components/loadingScreen';
import isConnected from '../../utils/isConnected';

const Home: NextPage = () => {
	// isConnected();

	return (
		<div>
			<Head>
				<title>next + ts</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
			</Head>
			<main>
				<LoadingScreen />
			</main>
		</div>
	);
};
export default Home;
