import type { NextPage } from 'next';
import Head from 'next/head';
import Router from 'next/router';
import Register from '../../components/register';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>next + ts</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
			</Head>
			<main>
				<Register />
			</main>
		</div>
	);
};
export default Home;
