import type { NextPage } from 'next';
import Head from 'next/head';
import WelcomePage from '../components/welcomePage';
import Register from '../components/register';
import { useSelector } from 'react-redux';
import { useState, useEffect } from 'react';
import { isEthBrowser } from '../utils/isEthBrowser';
import Contract from '../utils/contract';
import Router from 'next/router';

const Home: NextPage = () => {
	const [isRegister, setIsRegister] =
		useState<boolean>(true);

	const metamaskConnection = useSelector<any>(
		(state) => state.account.metamaskConnection
	);

	const account = useSelector<any>(
		(state) => state.account.account
	);

	isEthBrowser();

	useEffect(() => {
		const contract = Contract();
		if (metamaskConnection) {
			contract.methods
				.getIsRegistered()
				.call({
					from: account,
				})
				.then((result: boolean) => {
					setIsRegister(result);
				})
				.then(() => {
					if (isRegister) {
						Router.push('/panel');
					} else {
						Router.push('/register');
					}
				});
		}
	});
	return (
		<div>
			<Head>
				<title>next + ts</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
			</Head>
			<main>
				<WelcomePage />
			</main>
		</div>
	);
};
export default Home;
